import { NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import Test from "../components/Test";

const Home: NextPage = () => {
  return (
    <div className="bg-[#f5dfc3] h-screen snap-y snap-mandatory z-0 overflow-auto overflow-x-hidden scroll-smooth font-share">
      <Head>
        <title>My porto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Hero */}
      <section id="hero" className="snap-start">
        <Hero />
      </section>

      {/* About */}
      <section id="about" className="snap-center">
        <About />
      </section>

      {/* Skills */}
      <section id="skills" className="snap-start">
        <Skills />
      </section>

      {/* Projects */}
      <section id="projects" className="snap-center">
        <Projects />
      </section>

      {/* 3d Arts */}
      <section id="projects" className="snap-center">
        <Test />
      </section>
    </div>
  );
};

export default Home;
